[package]
name = "classfile-rs"
version = "0.1.0"
authors = ["mastercooker <c.o.okiedragon234@gmail.com>"]
edition = "2018"

[lib]
name = "classfile"
path = "src/lib.rs"

[[bin]]
name = "dissasembler"
path = "src/bin.rs"
[profile.release]
debug = true

[dependencies]
byteorder = "1.3.4"
